#!/bin/sh
# ARMv8 only
adb push android/libc++_shared.so /data/local/tmp
adb push android/hexagon_lib/libhalide_hexagon_remote_skel.so /data/local/tmp
# modify here for different signature files
adb push android/hexagon_lib/testsig-0xd82e3977.so /data/local/tmp
# modify here for ADSP or CDSP
adb push android/hexagon_lib/adsp/libhalide_hexagon_host.so /data/local/tmp

# generate .gray file by "convert IMAGE_FILE OUT_PUT.gray"
adb push cat.gray /data/local/tmp
# divmap.bin is generated by executing divmap_gen
adb push divmap.bin /data/local/tmp

adb shell "rm -f /data/local/tmp/out.gray"
adb push $1 /data/local/tmp
adb shell "cd /data/local/tmp; LD_LIBRARY_PATH=./ ./$1 cat.gray divmap.bin 3840 2160 11 0.0122 out.gray"
adb pull /data/local/tmp/out.gray
convert -size 3840x2160 -depth 8 out.gray out.png
