LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := gf_test

LOCAL_LDLIBS    := -lm -llog -lz

LOCAL_CFLAGS := -fsigned-char -UNDEBUG \
	-DBUILD="20141110" \
	-DC_ARITH_CODING_SUPPORTED=1 \
	-DD_ARITH_CODING_SUPPORTED=1 \
	-DBITS_IN_JSAMPLE=8 \
	-DHAVE_DLFCN_H=1 \
	-DHAVE_INTTYPES_H=1 \
	-DHAVE_LOCALE_H=1 \
	-DHAVE_MEMCPY=1 \
	-DHAVE_MEMORY_H=1 \
	-DHAVE_MEMSET=1 \
	-DHAVE_STDDEF_H=1 \
	-DHAVE_STDINT_H=1 \
	-DHAVE_STDLIB_H=1 \
	-DHAVE_STRINGS_H=1 \
	-DHAVE_STRING_H=1 \
	-DHAVE_SYS_STAT_H=1 \
	-DHAVE_SYS_TYPES_H=1 \
	-DHAVE_UNISTD_H=1 \
	-DHAVE_UNSIGNED_CHAR=1 \
	-DHAVE_UNSIGNED_SHORT=1 \
	-DINLINE="inline __attribute__((always_inline))" \
	-DJPEG_LIB_VERSION=62 \
	-DLIBJPEG_TURBO_VERSION="1.3.90" \
	-DMEM_SRCDST_SUPPORTED=1 \
	-DNEED_SYS_TYPES_H=1 \
	-DSTDC_HEADERS=1 \
	-DWITH_SIMD=1 \
	-D_GLIBCXX_DEPRECATED

LOCAL_CPPFLAGS := $(LOCAL_CFLAGS) -fexceptions -std=c++11

LOCAL_C_INCLUDES := $(LOCAL_PATH)/include $(LOCAL_PATH)/tools $(LOCAL_PATH)/aot

LOCAL_SRC_FILES := \
	gf.cpp

LOCAL_STATIC_LIBRARIES := libjpeg-turbo libpng

LOCAL_LDFLAGS := aot/guided_filter.a aot/fast_guided_filter.a

include $(BUILD_EXECUTABLE)
